wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight: 
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    columns: [35, 35, 35, 35]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    rows: [10, 10, 10, 10, 10]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    battery:
      type: power
      title: "⚡️"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 15
    ip:
      type: ipinfo
      title: "My IP"
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 0
        left: 3
        height: 1
        width: 3
      refreshInterval: 150
    security_info:
      type: security
      title: "Security"
      enabled: true
      position:
        top: 1
        left: 2
        height: 1
        width: 3
      refreshInterval: 300
    news:
      type: hackernews
      title: "HackerNews"
      enabled: true
      numberOfStories: 30
      position:
        top: 2
        left: 2
        height: 1
        width: 3
      storyType: top
      refreshInterval: 1000
    resources:
      type: resourceusage
      enabled: true
      position:
        top: 3
        left: 0
        height: 2
        width: 1
      refreshInterval: 1
    uptime:
      type: cmdrunner
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 4
        left: 1
        height: 1
        width: 3
      refreshInterval: 1
    disks:
      type: cmdrunner
      cmd: "df"
      args: ["-h"]
      enabled: true
      position:
        top: 3
        left: 1
        height: 1
        width: 3
      refreshInterval: 1
    git:
      commitCount: 5
      commitFormat: "[forestgreen]%h [grey]%cd [white]%s [grey]%an[white]"
      dateFormat: "%H:%M %d %b %y"
      enabled: true
      position:
        top: 0
        left: 0
        height: 3
        width: 2
      refreshInterval: 1
      repositories:
        - "/Users/mohamedanees/Documents/Work/JavaUtils"
